# Generated by Django 2.2.7 on 2019-11-07 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BookClub',
            fields=[
                ('BookClub_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('Profile_Pic', models.TextField(max_length=100000000)),
                ('Open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('Choice_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('Discussion_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.DateTimeField()),
                ('Title', models.CharField(max_length=100)),
                ('BookClub_ID', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Homepage.BookClub')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('Tag_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('profile_pic', models.TextField(default='https://cdn.business2community.com/wp-content/uploads/2017/08/blank-profile-picture-973460_640.png', max_length=100000000)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('Vote_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Choice_ID', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Homepage.Choice')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('Thread_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField(max_length=10000)),
                ('Time', models.DateTimeField()),
                ('Discussion_ID', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Homepage.Discussion')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('Poll_ID', models.AutoField(primary_key=True, serialize=False)),
                ('End_Time', models.DateField()),
                ('Title', models.CharField(default='No title', max_length=100)),
                ('BookClub_ID', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Homepage.BookClub')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('Meeting_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Location', models.CharField(max_length=250)),
                ('Time', models.DateTimeField()),
                ('Title', models.CharField(default='No title', max_length=500)),
                ('BookClub_ID', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Homepage.BookClub')),
            ],
        ),
        migrations.AddField(
            model_name='discussion',
            name='User_ID',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choice',
            name='Poll_ID',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Homepage.Poll'),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='Members',
            field=models.ManyToManyField(through='Homepage.Administrator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookclub',
            name='Tags',
            field=models.ManyToManyField(to='Homepage.Tag'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('Attendance_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Meeting_ID', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Homepage.Meeting')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='administrator',
            name='BookClub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homepage.BookClub'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
